name: Testing Pipeline

on:
  push:
    branches:
      - main    # Trigger the pipeline on changes to the main branch
  pull_request:
    branches:
      - main    # Trigger for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Use the JDK version required for your project

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        maven-version: '3.8.1'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests with Maven
      run: mvn test

    - name: Upload Test Results
      if: always()
      run: |
        mkdir -p test-results
        mv target/surefire-reports/*.xml test-results/
        echo "Test results uploaded!"
